<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click this button to hide the below ima_59be6a</name>
   <tag></tag>
   <elementGuidId>5db8e4b3-7f00-47fc-a7dd-055a18705393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='will-be-hidden']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#will-be-hidden</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>951e657e-e967-4268-8e6c-557845f54ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>will-be-hidden</value>
      <webElementGuid>e5b1c0fd-5651-4f5b-bf1a-09c7a526cc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../image/katalon-logo.png</value>
      <webElementGuid>5a0ea4ab-b18d-4f18-b1c5-9fc0447a1613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;will-be-hidden&quot;)</value>
      <webElementGuid>75e6956b-0660-43d9-8f92-a7c7b67f2c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='will-be-hidden']</value>
      <webElementGuid>e2ea8509-2fd7-48f9-84c4-84e1dea33877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>adff3db7-95ba-4f28-bbc3-467c384b0c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'will-be-hidden' and @src = '../image/katalon-logo.png']</value>
      <webElementGuid>8ceff30e-9779-4d4f-9b30-446043d816ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
